"""Canonical site chrome (Global Menu header + footer).

Single source of truth for the `<header class="site-header">` and
`<footer class="site-footer">` blocks that are otherwise duplicated across
~50 static pages. `build_site_chrome.py` injects the generated markup between
markers so future header/footer changes live in ONE place.

Design notes:
- **Behavior-preserving.** The generated markup reproduces the current
  header/footer exactly in *result* (same link targets, same active state,
  same ids used by JS). Internal link strings are normalized to be relative
  to the language root (`base`) so one template serves every page depth;
  self-links resolve to the same file they did before.
- **Two prefixes per page:**
    - `base` = relative path to the language root (repo root for JA, `en/`
      for EN). Used for in-app links (`app/…`, `setting/…`).
    - `img`  = relative path to the *repo-root* `images/` dir (images are
      shared by both languages). For JA `img == base`; for EN `img` has one
      extra `../`.
- `active` marks the current nav item (`annual` | `monthly` | `profit` | None).
"""

from __future__ import annotations

HEADER_MARK_START = "<!-- KPI-SITE-HEADER:START (generated by scripts/site_chrome.py — edit there) -->"
HEADER_MARK_END = "<!-- KPI-SITE-HEADER:END -->"
FOOTER_MARK_START = "<!-- KPI-SITE-FOOTER:START (generated by scripts/site_chrome.py — edit there) -->"
FOOTER_MARK_END = "<!-- KPI-SITE-FOOTER:END -->"

LABELS = {
    "ja": {
        "logo_href": "https://forge-laboratory.com",
        "logo_aria": "FORGE LABORATORY - トップページ",
        "nav_aria": "メインナビゲーション",
        "annual_label": "年次",
        "monthly_label": "月次",
        "daily_label": "日次",
        "profit_label": "考察",
        "annual_aria": "年間ビュー",
        "monthly_aria": "月間ビュー",
        "daily_aria": "日別ビューを開く",
        "daily_link_aria": "年次ページで日次ビュー（Daily）を開く",
        "profit_aria_inactive": "利益サマリー（プロプラン）。ベーシックの場合はプラン変更へ",
        "profit_aria_active": "利益サマリー（現在のページ）",
        "office_toggle_aria": "Office Mode に切り替え",
        "office_text": "OFFICE MODE",
        "menu_aria": "ナビゲーションメニューを開く",
        "gear_aria": "アカウント設定",
        "gear_tooltip": "設定",
        "popup_aria": "アカウント設定",
        "account_heading": "アカウント",
        "profile": "プロフィール",
        "preferences": "設定",
        "change_email": "メールアドレスの変更",
        "change_password": "パスワードの変更",
        "session": "セッション管理",
        "subscription_heading": "サブスクリプション",
        "plan_details": "プラン詳細",
        "change_plan": "プラン変更",
        "delete_account": "アカウント削除",
        "expense_label": "Expense",
        "expense_aria": "経費設定を開く（準備中）",
        "office_dropdown_aria": "Office Mode を切り替え",
        "office_dropdown_label": "Office Mode",
        "footer_backtotop_aria": "ページ先頭へ戻る",
        "dl_label": "DL",
        "dl_tooltip": "ダウンロード",
        "dl_aria": "雛形・収支データのダウンロード",
        "dl_menu_aria": "ダウンロードメニュー",
        "dl_heading": "雛形",
        "dl_daily": "支出雛形をダウンロード（日次）",
        "dl_monthly": "支出雛形をダウンロード（月次）",
        "dl_daily_file": "支出入力_日次_雛形.csv",
        "dl_monthly_file": "支出入力_月次_雛形.csv",
        "dl_data_heading": "データ出力",
        "dl_export_pl_mep": "収支データ（MEP＋PL）",
        "dl_export_pl_mep_aria": "MEPとPLの収支データをExcelでダウンロード（Pro）",
        "booking_label": "予約",
        "booking_aria": "予約台帳を開く（プロプラン）。ベーシックの場合はプラン変更へ",
    },
    "en": {
        "logo_href": "https://forge-laboratory.com/en",
        "logo_aria": "FORGE LABORATORY - Top page",
        "nav_aria": "Main navigation",
        "annual_label": "Annual",
        "monthly_label": "Monthly",
        "daily_label": "Daily",
        "profit_label": "Insight",
        "annual_aria": "Go to Annual view",
        "monthly_aria": "Go to Monthly view",
        "daily_aria": "Open Daily view",
        "daily_link_aria": "Open Daily from the Annual page",
        "profit_aria_inactive": "Profit summary (Pro). Basic plan goes to Change Plan",
        "profit_aria_active": "Profit summary (current page)",
        "office_toggle_aria": "Switch to Office Mode",
        "office_text": "OFFICE MODE",
        "menu_aria": "Open navigation menu",
        "gear_aria": "Account settings",
        "gear_tooltip": "Settings",
        "popup_aria": "Account Settings",
        "account_heading": "Account",
        "profile": "Profile",
        "preferences": "Preferences",
        "change_email": "Change Email",
        "change_password": "Change Password",
        "session": "Session Management",
        "subscription_heading": "Subscription",
        "plan_details": "Plan Details",
        "change_plan": "Change Plan",
        "delete_account": "Delete Account",
        "expense_label": "Expense",
        "expense_aria": "Open Expense (coming soon)",
        "office_dropdown_aria": "Toggle Office Mode",
        "office_dropdown_label": "Office Mode",
        "footer_backtotop_aria": "Back to top",
        "dl_label": "DL",
        "dl_tooltip": "Download",
        "dl_aria": "Download templates and P&L data",
        "dl_menu_aria": "Download menu",
        "dl_heading": "Templates",
        "dl_daily": "Download Expense Template (Daily)",
        "dl_monthly": "Download Expense Template (Monthly)",
        "dl_daily_file": "expense-import_daily_template.csv",
        "dl_monthly_file": "expense-import_monthly_template.csv",
        "dl_data_heading": "Data export",
        "dl_export_pl_mep": "P&L data (MEP + PL)",
        "dl_export_pl_mep_aria": "Download MEP and PL workbook as Excel (Pro)",
        "booking_label": "Booking",
        "booking_aria": "Open reservation ledger (Pro). Basic plan goes to Change Plan",
    },
    "zh-tw": {
        "logo_href": "https://forge-laboratory.com",
        "logo_aria": "FORGE LABORATORY - 首頁",
        "nav_aria": "主要導覽",
        "annual_label": "年度",
        "monthly_label": "月度",
        "daily_label": "每日",
        "profit_label": "洞察",
        "annual_aria": "年度檢視",
        "monthly_aria": "月度檢視",
        "daily_aria": "開啟每日檢視",
        "daily_link_aria": "在年度頁開啟每日檢視",
        "profit_aria_inactive": "利潤摘要（專業方案）。基本方案請前往變更方案",
        "profit_aria_active": "利潤摘要（目前頁面）",
        "office_toggle_aria": "切換至 Office Mode",
        "office_text": "OFFICE MODE",
        "menu_aria": "開啟導覽選單",
        "gear_aria": "帳戶設定",
        "gear_tooltip": "設定",
        "popup_aria": "帳戶設定",
        "account_heading": "帳戶",
        "profile": "個人資料",
        "preferences": "偏好設定",
        "change_email": "變更電子信箱",
        "change_password": "變更密碼",
        "session": "登入工作階段",
        "subscription_heading": "訂閱",
        "plan_details": "方案詳情",
        "change_plan": "變更方案",
        "delete_account": "刪除帳戶",
        "expense_label": "支出",
        "expense_aria": "開啟支出設定（準備中）",
        "office_dropdown_aria": "切換 Office Mode",
        "office_dropdown_label": "Office Mode",
        "footer_backtotop_aria": "回到頁首",
        "dl_label": "DL",
        "dl_tooltip": "下載",
        "dl_aria": "下載範本與收支資料",
        "dl_menu_aria": "下載選單",
        "dl_heading": "範本",
        "dl_daily": "下載支出範本（每日）",
        "dl_monthly": "下載支出範本（月度）",
        "dl_daily_file": "expense-import_daily_template.csv",
        "dl_monthly_file": "expense-import_monthly_template.csv",
        "dl_data_heading": "資料匯出",
        "dl_export_pl_mep": "損益資料（MEP＋PL）",
        "dl_export_pl_mep_aria": "下載 MEP 與 PL 的 Excel（專業方案）",
        "booking_label": "預約",
        "booking_aria": "開啟預約台帳（專業方案）。基本方案請前往變更方案",
    },
}

FOOTER_COPY = "© 2025 Forge-Laboratory. All rights reserved."

# Public (pre-login) pages — login / register / plan / legal — share a *minimal*
# chrome: logo + a Sci-Fi/Office mode toggle, no app nav and no account popup.
# This is a distinct design from the app header, so it has its own label set to
# preserve the exact current wording (e.g. JA text "オフィスモード", trailing-slash
# logo href) rather than being unified with the app header.
PUBLIC_LABELS = {
    "ja": {
        "logo_href": "https://forge-laboratory.com/",
        "logo_aria": "FORGE LABORATORY - トップページ",
        "office_aria": "オフィスモードに切り替え",
        "office_text": "オフィスモード",
    },
    "en": {
        "logo_href": "https://forge-laboratory.com/en",
        "logo_aria": "FORGE LABORATORY - Top page",
        "office_aria": "Switch to Office Mode",
        "office_text": "OFFICE MODE",
    },
    "zh-tw": {
        "logo_href": "https://forge-laboratory.com/",
        "logo_aria": "FORGE LABORATORY - 首頁",
        "office_aria": "切換至 Office Mode",
        "office_text": "OFFICE MODE",
    },
}


def _nav_simple(view: str, href: str, img: str, label: str, aria: str, active: bool, nav_attr: str = "") -> str:
    current = ' aria-current="page"' if active else ""
    return f"""          <li class="global-nav-item">
            <a href="{href}" class="nav-frame-btn"{nav_attr} aria-label="{aria}"{current}>
              <span class="btn-mode-frame">
                <img src="{img}images/button_frame.svg" alt="" class="btn-mode-frame-img" aria-hidden="true">
                <span class="btn-mode-text nav-btn-text">{label}</span>
              </span>
            </a>
          </li>"""


def _nav_daily(base: str, img: str, label: str, L: dict, daily_mode: str, nav_attr: str = "", daily_href: str | None = None) -> str:
    # "overlay": pages that host / open the Daily floating window (annual /
    #   monthly / profit-PL). href defaults to "#" but a page may pass a real
    #   deep link (e.g. monthly-edit → "../index.html?open=daily").
    # "link":    pages without the overlay navigate to Annual by default.
    if daily_mode == "link":
        href = daily_href or f"{base}app/annual/index.html"
        anchor = (
            f'            <a href="{href}" class="nav-frame-btn"{nav_attr} '
            f'aria-label="{L["daily_link_aria"]}">'
        )
    else:
        href = daily_href or "#"
        anchor = (
            f'            <a href="{href}" class="nav-frame-btn"{nav_attr} id="global-nav-daily-btn" '
            f'aria-label="{L["daily_aria"]}">'
        )
    return f"""          <li class="global-nav-item">
{anchor}
              <span class="btn-mode-frame">
                <img src="{img}images/button_frame.svg" alt="" class="btn-mode-frame-img" aria-hidden="true">
                <span class="btn-mode-text nav-btn-text">{label}</span>
              </span>
            </a>
          </li>"""


def _nav_profit(base: str, img: str, label: str, L: dict, active: bool, nav_attr: str = "", profit_href: str | None = None) -> str:
    href = profit_href or f"{base}app/profit/index.html"
    inner = f"""              <span class="btn-mode-frame">
                <img src="{img}images/button_frame.svg" alt="" class="btn-mode-frame-img" aria-hidden="true">
                <span class="btn-mode-text nav-btn-text">{label}</span>
              </span>"""
    if active:
        anchor = (
            f'            <a href="{href}" class="nav-frame-btn"{nav_attr} '
            f'aria-label="{L["profit_aria_active"]}" aria-current="page">\n'
            f"{inner}\n            </a>"
        )
    else:
        extra_attr = f"              {nav_attr.strip()}\n" if nav_attr.strip() else ""
        anchor = (
            f"            <a\n"
            f'              href="{href}"\n'
            f'              class="nav-frame-btn"\n'
            f"{extra_attr}"
            f'              id="global-nav-index-btn"\n'
            f'              data-href-pro="{href}"\n'
            f'              data-href-basic="{base}setting/change_plan.html"\n'
            f'              aria-label="{L["profit_aria_inactive"]}"\n'
            f"            >\n"
            f"{inner}\n            </a>"
        )
    return f"""          <li class="global-nav-item">
{anchor}
          </li>"""


def _account_link(href: str, label: str, key: str, current: str | None, danger: bool = False) -> str:
    cls = "account-settings-item"
    if danger:
        cls += " account-settings-item-danger"
    is_current = key == current
    if is_current:
        cls += " is-current"
    cur = ' aria-current="page"' if is_current else ""
    return f'<a href="{href}" class="{cls}" role="menuitem"{cur}>{label}</a>'


def build_header(
    lang: str,
    base: str,
    img: str,
    active: str | None,
    daily_mode: str = "overlay",
    profit_label: str | None = None,
    account_current: str | None = None,
    header_class: str = "",
    nav_class: str = "",
    nav_attr: str = "",
    daily_href: str | None = None,
    profit_href: str | None = None,
) -> str:
    """Canonical app header.

    Optional overrides let generated pages (monthly-edit, PL) reuse the same
    source while keeping their page-specific nav wiring:
    - `header_class` / `nav_class`: extra classes (e.g. `pl-site-header`).
    - `nav_attr`: attribute string added to every nav `<a>` (e.g. the PL
      leave-guard's ` data-pl-nav="1"`). Must start with a space.
    - `daily_href` / `profit_href`: deep-link targets (e.g. `?open=daily`).
    """
    L = LABELS[lang]
    header_cls = f"site-header {header_class}".strip()
    nav_cls = f"global-nav {nav_class}".strip()
    items = "\n".join(
        [
            _nav_simple(
                "annual", f"{base}app/annual/index.html", img,
                L["annual_label"], L["annual_aria"], active == "annual", nav_attr,
            ),
            _nav_simple(
                "monthly", f"{base}app/monthly/index.html", img,
                L["monthly_label"], L["monthly_aria"], active == "monthly", nav_attr,
            ),
            _nav_daily(base, img, L["daily_label"], L, daily_mode, nav_attr, daily_href),
            _nav_profit(base, img, profit_label or L["profit_label"], L, active == "profit", nav_attr, profit_href),
        ]
    )
    return f"""  <header class="{header_cls}">
    <div class="header-inner">
      <div class="header-logo">
        <a href="{L['logo_href']}" class="logo-link" aria-label="{L['logo_aria']}" target="_blank" rel="noopener noreferrer">
          <img src="{img}images/forge_lab_logo.png" alt="FORGE LABORATORY" class="logo-img">
        </a>
      </div>
      <nav class="{nav_cls}" aria-label="{L['nav_aria']}">
        <ul class="global-nav-list">
{items}
        </ul>
      </nav>
      <div class="header-actions">
        <a href="#" class="btn-mode" id="btn-mode-toggle" role="button" aria-label="{L['office_toggle_aria']}">
          <span class="btn-mode-frame">
            <img src="{img}images/button_frame.svg" alt="" class="btn-mode-frame-img" aria-hidden="true">
            <span class="btn-mode-text" id="btn-mode-text">{L['office_text']}</span>
          </span>
        </a>
        <a
          href="{base}app/booking/index.html"
          class="header-booking-btn kpi-chrome-tip"
          id="header-booking-btn"
          data-href-pro="{base}app/booking/index.html"
          data-href-basic="{base}setting/change_plan.html"
          data-kpi-pro-gate
          aria-label="{L['booking_aria']}"
          data-kpi-tutorial-tip
          data-tooltip="{L['booking_label']}"
        >
          <img
            src="{img}images/booking_sci-fi.svg"
            alt=""
            class="header-booking-btn__img header-booking-btn__img--scifi"
            aria-hidden="true"
            width="24"
            height="24"
          >
          <img
            src="{img}images/booking_office.svg"
            alt=""
            class="header-booking-btn__img header-booking-btn__img--office"
            aria-hidden="true"
            width="24"
            height="24"
          >
        </a>
        <details class="header-dl" id="header-dl">
          <summary
            class="header-dl-btn kpi-chrome-tip"
            aria-label="{L['dl_aria']}"
            data-kpi-tutorial-tip
            data-tooltip="{L['dl_tooltip']}"
          >{L['dl_label']}</summary>
          <div class="template-dl-menu" role="menu" aria-label="{L['dl_menu_aria']}">
            <p class="template-dl-heading">{L['dl_heading']}</p>
            <a href="{img}excel/{L['dl_daily_file']}" download class="template-dl-item" role="menuitem">{L['dl_daily']}</a>
            <a href="{img}excel/{L['dl_monthly_file']}" download class="template-dl-item" role="menuitem">{L['dl_monthly']}</a>
            <hr class="template-dl-sep" aria-hidden="true">
            <p class="template-dl-heading">{L['dl_data_heading']}</p>
            <button type="button" class="template-dl-item template-dl-item--export" id="kpi-export-pl-mep" role="menuitem" data-kpi-change-plan="{base}setting/change_plan.html" aria-label="{L['dl_export_pl_mep_aria']}">{L['dl_export_pl_mep']}</button>
          </div>
        </details>
        <button type="button" class="icon-button icon-button-menu" aria-label="{L['menu_aria']}">
          <img src="{img}images/dropdown_menu.svg" alt="" class="icon-img" aria-hidden="true">
        </button>
        <button
          type="button"
          class="icon-button icon-button-settings kpi-chrome-tip"
          id="btn-account-settings"
          aria-label="{L['gear_aria']}"
          aria-expanded="false"
          aria-haspopup="true"
          data-kpi-tutorial-tip
          data-tooltip="{L['gear_tooltip']}"
        >
          <img src="{img}images/setting_gear.svg" alt="" class="icon-img" aria-hidden="true">
        </button>
      </div>
      <div class="account-settings-popup" id="account-settings-popup" role="menu" aria-label="{L['popup_aria']}" hidden>
        <h3 class="account-settings-popup-title">{L['popup_aria']}</h3>
        <section class="account-settings-section">
          <h4 class="account-settings-heading">{L['account_heading']}</h4>
          <nav class="account-settings-nav">
            {_account_link(f"{base}setting/profile.html", L['profile'], 'profile', account_current)}
            {_account_link(f"{base}setting/preferences.html", L['preferences'], 'preferences', account_current)}
            {_account_link(f"{base}setting/change_email.html", L['change_email'], 'change_email', account_current)}
            {_account_link(f"{base}setting/change_password.html", L['change_password'], 'change_password', account_current)}
            {_account_link(f"{base}setting/session_management.html", L['session'], 'session', account_current)}
          </nav>
        </section>
        <section class="account-settings-section">
          <h4 class="account-settings-heading">{L['subscription_heading']}</h4>
          <nav class="account-settings-nav">
            {_account_link(f"{base}setting/plan_details.html", L['plan_details'], 'plan_details', account_current)}
            {_account_link(f"{base}setting/change_plan.html", L['change_plan'], 'change_plan', account_current)}
          </nav>
        </section>
        <div class="account-settings-sep"></div>
        {_account_link(f"{base}setting/delete_account1.html", L['delete_account'], 'delete', account_current, danger=True)}
      </div>
      <div class="settings-dropdown" id="settings-dropdown" hidden>
        <div class="settings-dropdown-inner">
          <a href="#" class="nav-frame-btn settings-dropdown-item" aria-label="{L['expense_aria']}">
            <span class="btn-mode-frame">
              <img src="{img}images/button_frame.svg" alt="" class="btn-mode-frame-img" aria-hidden="true">
              <span class="btn-mode-text nav-btn-text">{L['expense_label']}</span>
            </span>
          </a>
          <a href="#" class="nav-frame-btn settings-dropdown-item" id="settings-office-toggle" aria-label="{L['office_dropdown_aria']}">
            <span class="btn-mode-frame">
              <img src="{img}images/button_frame.svg" alt="" class="btn-mode-frame-img" aria-hidden="true">
              <span class="btn-mode-text nav-btn-text" id="settings-office-label">{L['office_dropdown_label']}</span>
            </span>
          </a>
        </div>
      </div>
    </div>
    <script src="{img}js/kpi-auth-client.js"></script>
    <script>
    (function () {{
      if (window.__headerDlBound) return;
      window.__headerDlBound = true;
      document.addEventListener('click', function (e) {{
        var dl = document.getElementById('header-dl');
        if (dl && dl.open && !dl.contains(e.target)) dl.removeAttribute('open');
      }});
      document.addEventListener('keydown', function (e) {{
        if (e.key !== 'Escape') return;
        var dl = document.getElementById('header-dl');
        if (dl && dl.open) dl.removeAttribute('open');
      }});
    }})();
    (function () {{
      if (!window.__KPI_AUTH) return;
      try {{
        if (typeof window.__KPI_AUTH.syncPlanFromServer === 'function') {{
          window.__KPI_AUTH.syncPlanFromServer().catch(function () {{}});
        }}
        if (typeof window.__KPI_AUTH.bindInsightNavGate === 'function') {{
          window.__KPI_AUTH.bindInsightNavGate(document);
        }}
      }} catch (_e) {{}}
    }})();
    </script>
  </header>"""


def build_footer(lang: str, img: str) -> str:
    L = LABELS[lang]
    return f"""  <footer class="site-footer">
    <button class="footer-backtotop" id="footerBackToTop" aria-label="{L['footer_backtotop_aria']}">
      <img src="{img}images/arrow_up.svg" alt="" class="footer-backtotop__icon" aria-hidden="true">
    </button>
    <div class="footer-separator"></div>
    <div class="footer-logo">
      <a href="{L['logo_href']}" class="logo-link" aria-label="{L['logo_aria']}" target="_blank" rel="noopener noreferrer">
        <img src="{img}images/forge_lab_logo.png" alt="FORGE LABORATORY" class="logo-img">
      </a>
    </div>
    <p class="footer-copy">{FOOTER_COPY}</p>
  </footer>"""


def build_public_header(lang: str, img: str) -> str:
    """Minimal header for pre-login pages (login / register / plan / legal).

    Logo + mode toggle only. Keeps the ids used by each page's inline mode JS
    (`btn-mode-toggle`, `btn-mode-text`).
    """
    L = PUBLIC_LABELS[lang]
    return f"""  <header class="site-header">
    <div class="header-inner">
      <div class="header-logo">
        <a href="{L['logo_href']}" class="logo-link" aria-label="{L['logo_aria']}" target="_blank" rel="noopener noreferrer">
          <img src="{img}images/forge_lab_logo.png" alt="FORGE LABORATORY" class="logo-img">
        </a>
      </div>
      <div class="header-actions">
        <a href="#" class="btn-mode" id="btn-mode-toggle" role="button" aria-label="{L['office_aria']}">
          <span class="btn-mode-frame">
            <img src="{img}images/button_frame.svg" alt="" class="btn-mode-frame-img" aria-hidden="true">
            <span class="btn-mode-text" id="btn-mode-text">{L['office_text']}</span>
          </span>
        </a>
      </div>
    </div>
  </header>"""


def build_public_footer(lang: str, img: str) -> str:
    """Minimal footer for pre-login pages: separator + logo + copyright.

    No back-to-top button (these pages are short).
    """
    L = PUBLIC_LABELS[lang]
    return f"""  <footer class="site-footer">
    <div class="footer-separator"></div>
    <div class="footer-logo">
      <a href="{L['logo_href']}" class="logo-link" aria-label="{L['logo_aria']}" target="_blank" rel="noopener noreferrer">
        <img src="{img}images/forge_lab_logo.png" alt="FORGE LABORATORY" class="logo-img">
      </a>
    </div>
    <p class="footer-copy">{FOOTER_COPY}</p>
  </footer>"""
