"""Canonical site chrome (Global Menu header + footer).

Single source of truth for the `<header class="site-header">` and
`<footer class="site-footer">` blocks that are otherwise duplicated across
~50 static pages. `build_site_chrome.py` injects the generated markup between
markers so future header/footer changes live in ONE place.

Design notes:
- **Behavior-preserving.** The generated markup reproduces the current
  header/footer exactly in *result* (same link targets, same active state,
  same ids used by JS). Internal link strings are normalized to be relative
  to the language root (`base`) so one template serves every page depth;
  self-links resolve to the same file they did before.
- **Two prefixes per page:**
    - `base` = relative path to the language root (repo root for JA, `en/`
      for EN). Used for in-app links (`app/…`, `setting/…`).
    - `img`  = relative path to the *repo-root* `images/` dir (images are
      shared by both languages). For JA `img == base`; for EN `img` has one
      extra `../`.
- `active` marks the current nav item (`annual` | `monthly` | `profit` | None).
"""

from __future__ import annotations

HEADER_MARK_START = "<!-- KPI-SITE-HEADER:START (generated by scripts/site_chrome.py — edit there) -->"
HEADER_MARK_END = "<!-- KPI-SITE-HEADER:END -->"
FOOTER_MARK_START = "<!-- KPI-SITE-FOOTER:START (generated by scripts/site_chrome.py — edit there) -->"
FOOTER_MARK_END = "<!-- KPI-SITE-FOOTER:END -->"

LABELS = {
    "ja": {
        "logo_href": "https://forge-laboratory.com",
        "logo_aria": "FORGE LABORATORY - トップページ",
        "nav_aria": "メインナビゲーション",
        "annual_label": "年次",
        "monthly_label": "月次",
        "daily_label": "日次",
        "profit_label": "考察",
        "annual_aria": "年間ビュー",
        "monthly_aria": "月間ビュー",
        "daily_aria": "日別ビューを開く",
        "daily_link_aria": "年次ページで日次ビュー（Daily）を開く",
        "profit_aria_inactive": "利益サマリー（プロプラン）。ベーシックの場合はプラン変更へ",
        "profit_aria_active": "利益サマリー（現在のページ）",
        "office_toggle_aria": "Office Mode に切り替え",
        "office_text": "OFFICE MODE",
        "menu_aria": "ナビゲーションメニューを開く",
        "gear_aria": "アカウント設定",
        "popup_aria": "アカウント設定",
        "account_heading": "Account",
        "profile": "Profile",
        "change_email": "メールアドレスの変更",
        "change_password": "パスワードの変更",
        "session": "セッション管理",
        "subscription_heading": "Subscription",
        "plan_details": "プラン詳細",
        "change_plan": "プラン変更",
        "delete_account": "アカウント削除",
        "expense_label": "Expense",
        "expense_aria": "経費設定を開く（準備中）",
        "office_dropdown_aria": "Office Mode を切り替え",
        "office_dropdown_label": "Office Mode",
        "footer_backtotop_aria": "ページ先頭へ戻る",
    },
    "en": {
        "logo_href": "https://forge-laboratory.com/en",
        "logo_aria": "FORGE LABORATORY - Top page",
        "nav_aria": "Main navigation",
        "annual_label": "Annual",
        "monthly_label": "Monthly",
        "daily_label": "Daily",
        "profit_label": "Insight",
        "annual_aria": "Go to Annual view",
        "monthly_aria": "Go to Monthly view",
        "daily_aria": "Open Daily view",
        "daily_link_aria": "Open Daily from the Annual page",
        "profit_aria_inactive": "Profit summary (Pro). Basic plan goes to Change Plan",
        "profit_aria_active": "Profit summary (current page)",
        "office_toggle_aria": "Switch to Office Mode",
        "office_text": "OFFICE MODE",
        "menu_aria": "Open navigation menu",
        "gear_aria": "Account settings",
        "popup_aria": "Account Settings",
        "account_heading": "Account",
        "profile": "Profile",
        "change_email": "Change Email",
        "change_password": "Change Password",
        "session": "Session Management",
        "subscription_heading": "Subscription",
        "plan_details": "Plan Details",
        "change_plan": "Change Plan",
        "delete_account": "Delete Account",
        "expense_label": "Expense",
        "expense_aria": "Open Expense (coming soon)",
        "office_dropdown_aria": "Toggle Office Mode",
        "office_dropdown_label": "Office Mode",
        "footer_backtotop_aria": "Back to top",
    },
}

FOOTER_COPY = "© 2025 Forge-Laboratory. All rights reserved."


def _nav_simple(view: str, href: str, img: str, label: str, aria: str, active: bool) -> str:
    current = ' aria-current="page"' if active else ""
    return f"""          <li class="global-nav-item">
            <a href="{href}" class="nav-frame-btn" aria-label="{aria}"{current}>
              <span class="btn-mode-frame">
                <img src="{img}images/button_frame.svg" alt="" class="btn-mode-frame-img" aria-hidden="true">
                <span class="btn-mode-text nav-btn-text">{label}</span>
              </span>
            </a>
          </li>"""


def _nav_daily(base: str, img: str, label: str, L: dict, daily_mode: str) -> str:
    # "overlay": pages that host the Daily floating window (annual / monthly).
    # "link":    pages without the overlay (e.g. profit) navigate to Annual.
    if daily_mode == "link":
        anchor = (
            f'            <a href="{base}app/annual/index.html" class="nav-frame-btn" '
            f'aria-label="{L["daily_link_aria"]}">'
        )
    else:
        anchor = (
            f'            <a href="#" class="nav-frame-btn" id="global-nav-daily-btn" '
            f'aria-label="{L["daily_aria"]}">'
        )
    return f"""          <li class="global-nav-item">
{anchor}
              <span class="btn-mode-frame">
                <img src="{img}images/button_frame.svg" alt="" class="btn-mode-frame-img" aria-hidden="true">
                <span class="btn-mode-text nav-btn-text">{label}</span>
              </span>
            </a>
          </li>"""


def _nav_profit(base: str, img: str, label: str, L: dict, active: bool) -> str:
    href = f"{base}app/profit/index.html"
    inner = f"""              <span class="btn-mode-frame">
                <img src="{img}images/button_frame.svg" alt="" class="btn-mode-frame-img" aria-hidden="true">
                <span class="btn-mode-text nav-btn-text">{label}</span>
              </span>"""
    if active:
        anchor = (
            f'            <a href="{href}" class="nav-frame-btn" '
            f'aria-label="{L["profit_aria_active"]}" aria-current="page">\n'
            f"{inner}\n            </a>"
        )
    else:
        anchor = (
            f"            <a\n"
            f'              href="{href}"\n'
            f'              class="nav-frame-btn"\n'
            f'              id="global-nav-index-btn"\n'
            f'              data-href-pro="{href}"\n'
            f'              data-href-basic="{base}setting/change_plan.html"\n'
            f'              aria-label="{L["profit_aria_inactive"]}"\n'
            f"            >\n"
            f"{inner}\n            </a>"
        )
    return f"""          <li class="global-nav-item">
{anchor}
          </li>"""


def _account_link(href: str, label: str, key: str, current: str | None, danger: bool = False) -> str:
    cls = "account-settings-item"
    if danger:
        cls += " account-settings-item-danger"
    is_current = key == current
    if is_current:
        cls += " is-current"
    cur = ' aria-current="page"' if is_current else ""
    return f'<a href="{href}" class="{cls}" role="menuitem"{cur}>{label}</a>'


def build_header(
    lang: str,
    base: str,
    img: str,
    active: str | None,
    daily_mode: str = "overlay",
    profit_label: str | None = None,
    account_current: str | None = None,
) -> str:
    L = LABELS[lang]
    items = "\n".join(
        [
            _nav_simple(
                "annual", f"{base}app/annual/index.html", img,
                L["annual_label"], L["annual_aria"], active == "annual",
            ),
            _nav_simple(
                "monthly", f"{base}app/monthly/index.html", img,
                L["monthly_label"], L["monthly_aria"], active == "monthly",
            ),
            _nav_daily(base, img, L["daily_label"], L, daily_mode),
            _nav_profit(base, img, profit_label or L["profit_label"], L, active == "profit"),
        ]
    )
    return f"""  <header class="site-header">
    <div class="header-inner">
      <div class="header-logo">
        <a href="{L['logo_href']}" class="logo-link" aria-label="{L['logo_aria']}" target="_blank" rel="noopener noreferrer">
          <img src="{img}images/forge_lab_logo.png" alt="FORGE LABORATORY" class="logo-img">
        </a>
      </div>
      <nav class="global-nav" aria-label="{L['nav_aria']}">
        <ul class="global-nav-list">
{items}
        </ul>
      </nav>
      <div class="header-actions">
        <a href="#" class="btn-mode" id="btn-mode-toggle" role="button" aria-label="{L['office_toggle_aria']}">
          <span class="btn-mode-frame">
            <img src="{img}images/button_frame.svg" alt="" class="btn-mode-frame-img" aria-hidden="true">
            <span class="btn-mode-text" id="btn-mode-text">{L['office_text']}</span>
          </span>
        </a>
        <button type="button" class="icon-button icon-button-menu" aria-label="{L['menu_aria']}">
          <img src="{img}images/dropdown_menu.svg" alt="" class="icon-img" aria-hidden="true">
        </button>
        <button type="button" class="icon-button icon-button-settings" id="btn-account-settings" aria-label="{L['gear_aria']}" aria-expanded="false" aria-haspopup="true">
          <img src="{img}images/setting_gear.svg" alt="" class="icon-img" aria-hidden="true">
        </button>
      </div>
      <div class="account-settings-popup" id="account-settings-popup" role="menu" aria-label="{L['popup_aria']}" hidden>
        <h3 class="account-settings-popup-title">Account Settings</h3>
        <section class="account-settings-section">
          <h4 class="account-settings-heading">{L['account_heading']}</h4>
          <nav class="account-settings-nav">
            {_account_link(f"{base}setting/profile.html", L['profile'], 'profile', account_current)}
            {_account_link(f"{base}setting/change_email.html", L['change_email'], 'change_email', account_current)}
            {_account_link(f"{base}setting/change_password.html", L['change_password'], 'change_password', account_current)}
            {_account_link(f"{base}setting/session_management.html", L['session'], 'session', account_current)}
          </nav>
        </section>
        <section class="account-settings-section">
          <h4 class="account-settings-heading">{L['subscription_heading']}</h4>
          <nav class="account-settings-nav">
            {_account_link(f"{base}setting/plan_details.html", L['plan_details'], 'plan_details', account_current)}
            {_account_link(f"{base}setting/change_plan.html", L['change_plan'], 'change_plan', account_current)}
          </nav>
        </section>
        <div class="account-settings-sep"></div>
        {_account_link(f"{base}setting/delete_account1.html", L['delete_account'], 'delete', account_current, danger=True)}
      </div>
      <div class="settings-dropdown" id="settings-dropdown" hidden>
        <div class="settings-dropdown-inner">
          <a href="#" class="nav-frame-btn settings-dropdown-item" aria-label="{L['expense_aria']}">
            <span class="btn-mode-frame">
              <img src="{img}images/button_frame.svg" alt="" class="btn-mode-frame-img" aria-hidden="true">
              <span class="btn-mode-text nav-btn-text">{L['expense_label']}</span>
            </span>
          </a>
          <a href="#" class="nav-frame-btn settings-dropdown-item" id="settings-office-toggle" aria-label="{L['office_dropdown_aria']}">
            <span class="btn-mode-frame">
              <img src="{img}images/button_frame.svg" alt="" class="btn-mode-frame-img" aria-hidden="true">
              <span class="btn-mode-text nav-btn-text" id="settings-office-label">{L['office_dropdown_label']}</span>
            </span>
          </a>
        </div>
      </div>
    </div>
  </header>"""


def build_footer(lang: str, img: str) -> str:
    L = LABELS[lang]
    return f"""  <footer class="site-footer">
    <button class="footer-backtotop" id="footerBackToTop" aria-label="{L['footer_backtotop_aria']}">
      <img src="{img}images/arrow_up.svg" alt="" class="footer-backtotop__icon" aria-hidden="true">
    </button>
    <div class="footer-separator"></div>
    <div class="footer-logo">
      <a href="{L['logo_href']}" class="logo-link" aria-label="{L['logo_aria']}" target="_blank" rel="noopener noreferrer">
        <img src="{img}images/forge_lab_logo.png" alt="FORGE LABORATORY" class="logo-img">
      </a>
    </div>
    <p class="footer-copy">{FOOTER_COPY}</p>
  </footer>"""
